### ISSUE TITLE
Automated releases

### ISSUE THREAD

**Issue by jastice** [scredis/scredis#1]
Set up automated releases and snapshots, possibly with Travis CI and Bintray, or whatever seems practical.

**Comment by KarelCemus** [comment]
Hi, is there any progress on this issue? I am gonna need it soon released with "recent" changes including Scala 2.12 support. Is there anything I can do to make it resolved and released soon? If so, please give me as many details as possible, I'd look at it.

I am interested in:

- available latest snapshot in maven repo
- released stable 2.1.0 with Scala 2.12

Thanks

**Comment by jastice** [comment]
Sorry I kind of missed this. The current progress is that I registered an account on Sonatype ;)
To get current versions Jitpack seems to work.

If you'd still like to work on setting this up, I can give you the necessary privileges.

**Comment by KarelCemus** [comment]
Thanks for the update, however, I'm sorry, I have already workaround it.

**Comment by kpbochenek** [comment]
Releasing is described in section [Releasing](https://github.com/scredis/scredis#releasing).

It is almost fully automated, there is one more step needed to automatically push artifacts from bintray to maven central. Solution is to execute [API call](https://bintray.com/docs/api/#_sync_version_artifacts_to_maven_central) at the end of travis build to perform sync.

Work In Progress :)

**Comment by kpbochenek** [comment]
Releases are automatically pushed to bintray, only sync to maven central must be performed manually but is well described in [Releasing](https://github.com/scredis/scredis#releasing) and is almost instant.
On the other hand automating it is very complicated and releases are not performed frequently.

In my opinion it is not worth automating it for now.

Closing and in case of returning need for it please open a new issue.
