### ISSUE TITLE
User-specific path in test config

### ISSUE THREAD

**Issue by jastice** [scredis/scredis#13]
A test config is using a user-specific path:
https://github.com/rssh/scredis/blob/master/src/test/resources/redis-6380.conf#L187
This isn't so great when we want tests to be independent of user environment and fully automated testing (#2)

**Comment by kpbochenek** [comment]
Fixed on master branch.
Currently required directory is: "/tmp/redis-6380"
It is automatically created by travis for automated testing.
And for local testing it is already included in script for starting redis.
