### ISSUE TITLE
scredis 2.4.1 not released for scala 2.13

### ISSUE THREAD

**Issue by Philippus** [scredis/scredis#149]
It looks like scredis 2.4.1 was not released for scala 2.13, only for scala 2.11 and scala 2.12.
The latest release for scala 2.13 is 2.3.6: https://search.maven.org/artifact/com.github.scredis/scredis_2.13.

**Comment by kpbochenek** [comment]
Thanks for reporting! I will try to release a new version today and will double check version for 2.13 is also released.

**Comment by kpbochenek** [comment]
sad story,
We use travis-ci to do releasing/publishing.
Travis offers only openjdk 11.0.2 which has a bug that breaks releasing process for 2.13.
It is impossible to request specific version of openjdk in travis build, e.g. `11.0.8`.
I cannot release it manually as only @jastice has original credentials and ones available in travis are encoded and can only be decoded by travis builds.

2.4.2 is only available for 2.11 and 2.12.

I will try force jdk8 and see what happens, maybe 2.4.3 will be more successful. 
But it also looks like travis takes >2h for builds to even start which doesn't help at all.

**Comment by kpbochenek** [comment]
2.4.3 released properly for 2.11-2.13. (it takes a while to populate to mvnrepository, already available in bintray)

@Philippus thanks for noticing this and reporting :+1:
