### ISSUE TITLE
Streams support

### ISSUE THREAD

**Issue by kardapoltsev** [scredis/scredis#185]
Hello!
I'd like to implement redis streams in your library. Do you have any work on it? I have some time to add this functionality but just want to be sure that my help will be welcome.

**Comment by kpbochenek** [comment]
Hi!
There was no effort done towards redis streams at all so far. Contribution would be gladly appreciated :+1: 
I cannot really point you how this could/should be implemented as I haven't had a chance to take a look at this.

**Comment by kardapoltsev** [comment]
Ok, I'll try to make PR soon.
