### ISSUE TITLE
Migrate documentation to in-repo version

### ISSUE THREAD

**Issue by jastice** [scredis/scredis#19]
sbt-site allows automated creation of documentation from sources in the repository. This is preferable to the Wiki because it is versioned along with the repo itself.

See also #8, #3

**Comment by kpbochenek** [comment]
Documentation is generated from in-repo templates.
Published and available under url: https://scredis.github.io/scredis/
How to work with documentation is described in dedicated section in README: https://github.com/scredis/scredis#documentation
