### ISSUE TITLE
2.1.0-SNAPSHOT release

### ISSUE THREAD

**Issue by akalinovskiy** [scredis/scredis#22]
I can find '2.1.0-SNAPSHOT' version at oss.sonatype.org. Could you release a version or RC with upgraded dependencies for 'typesafe.config' and 'akka-actor'?

**Comment by jastice** [comment]
I haven't had the time to set up a release process, so for the moment you'll have to publish it to your own repo or help with the setup (see #1) :)

**Comment by jastice** [comment]
Also, it should be already possible to use the library via Jitpack. Use this setup:
```
resolvers += "jitpack" at "https://jitpack.io"

libraryDependencies += "com.github.scredis" %% "scredis" % "dd45255a1f2034a72fc8522bc407fc4b6f2d6ad9" // or any other commit hash
```

**Comment by jastice** [comment]
There is now continuous releases of "snapshot" versions to bintray:

https://bintray.com/jastice/maven/scredis/

```
resolvers += Resolver.bintrayIvyRepo("jastice","maven")
libraryDependencies += "com.github.scredis" %% "scredis" % "<version>"
```
