### ISSUE TITLE
Is project dead?

### ISSUE THREAD

**Issue by nandrienko** [scredis/scredis#28]
Hi,

I'm wondering whether this project is dead. I needed to use RedisCluster, but its implementation is far from being neat as it creates new ActorSystem per connection. In case this project is still alive, I can send a PR some time later which reuses same ActorSystem among connections to each node as well as allows pass client's owned ActorSystem.

**Comment by jastice** [comment]
I am technically maintaining the project and will accept any reasonable pull requests, but can't currently do development. If you contribute anything, I'll be happy to add you to the scredis organization as well.
