### ISSUE TITLE
Does scredis support readonly to only read from slave and not master ? 

### ISSUE THREAD

**Issue by amishra123** [scredis/scredis#33]
I didn't find support for readonly in scredis but just wanted to double-check in case i missed it.
Is there a way i can do hmget only from slaves.I don't want it to read from master as those are getting throttled.So I want to mark it readonly when creating a RedisCluster to read from slaves.
Do you have suggestions/idea?

**Comment by jastice** [comment]
This is not implemented, but you're welcome to contribute :)
The place to start looking is in [`ClusterConnection`](https://github.com/scredis/scredis/blob/2de55ed02ea232254b4a1294fd4b9a75b8287160/src/main/scala/scredis/io/ClusterConnection.scala#L245-L252)

**Comment by amishra123** [comment]
okay.cool.thanks for getting back.
