### ISSUE TITLE
Old LazyLogging version

### ISSUE THREAD

**Issue by eugenemiretsky** [scredis/scredis#34]
Hi, 

I get the error 
```
'Symbol 'type com.typesafe.scalalogging.Logging' is missing from the classpath`
[error] This symbol is required by 'trait com.typesafe.scalalogging.slf4j.LazyLogging'.
[error] Make sure that type Logging is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'LazyLogging.class' was compiled against an incompatible version of com.typesafe.scalalogging.`
```

I think it has to do with me using scala-logging 3.9.0 (one of my dependencies requires it), while scredis uses version 3.1.0

When just including the dependencies I run into the following issue
https://github.com/lightbend/scala-logging/issues/16
https://github.com/lightbend/scala-logging/issues/68

However, when I follow the advice in the links and exclude 'scala-logging-api_2.11', I get the error I posted.

**Comment by kpbochenek** [comment]
@eugenemiretsky I have updated `scala-logging` to version `3.9.0` in newest release.

I hope this will fix your issue but I have no way of testing it.

I will close this ticket and if you encounter any problems with new release please open a new one and we will work on that.
