### ISSUE TITLE
ActorSystem in ClusterConnection

### ISSUE THREAD

**Issue by CharlesAHunt** [scredis/scredis#35]
'ClusterConnection' creates a new ActorSystem for every connection in 'makeConnection'.

Creating an ActorSystem is expensive, so Scredis should avoid creating a new one each time it needs a new connection, should be using a single system for all connection, unless there is a good reason for them not to.

Also, the Scredis user is not able to pass in her own ActorSystem if she wants to reuse an existing one or pass in some specialized/custom system.

**Comment by jastice** [comment]
Hi! This repo is currently "passively" maintained. So any reasonable pull request will be merged, but nobody currently is investing time for fixes.

**Comment by kpbochenek** [comment]
This is fixed with:
https://github.com/scredis/scredis/commit/bcda5cd8724a9822ea86cfd45059395b9bd2797b

in `RedisCluster.apply` you have additional parameter `systemOpt:Option[ActorSystem]`.
