### ISSUE TITLE
Merge unhandled pull requests from Livestream/scredis

### ISSUE THREAD

**Issue by jastice** [scredis/scredis#5]
Several pull requests merit merging, but haven't been incorporated to Livestream's scredis repo. Merge them if it makes sense.
- [x] https://github.com/Livestream/scredis/pull/36
- [x] https://github.com/Livestream/scredis/pull/44
- [x] https://github.com/Livestream/scredis/pull/51

**Comment by kpbochenek** [comment]
"Simple updates for MaxConcurrentRequests"
Livestream/scredis#44

I copy&pasted changes and created PR for this repository https://github.com/scredis/scredis/pull/44
Will merge when tests pass.
